# TP 2

In [1]:
import gymnasium as gym
import numpy as np

### Exercise 1: Explore the FrozenLake environment from OpenAI Gym.

Charger l’environnement FrozenLake-v1 de OpenAI Gym 

In [2]:
env =gym.make("FrozenLake-v1",is_slippery=True)

Afficher les informations de l'espace d'états et d'actions

In [3]:
print("Espace d'états:", env.observation_space.n)
print("Espace d'actions:", env.action_space.n)

Espace d'états: 16
Espace d'actions: 4


Exécuter une boucle avec des actions aléatoires

In [4]:
num_episodes = 10
for episode in range(num_episodes):
    state = env.reset()
    done = False
    total_reward = 0
    
    while not done:
        action = env.action_space.sample()  # Action aléatoire
        next_state, reward, done, info,_= env.step(action)
        total_reward += reward
        state = next_state
    print(f"Épisode {episode + 1}, Récompense totale: {total_reward}")

Épisode 1, Récompense totale: 0.0
Épisode 2, Récompense totale: 0.0
Épisode 3, Récompense totale: 0.0
Épisode 4, Récompense totale: 0.0
Épisode 5, Récompense totale: 0.0
Épisode 6, Récompense totale: 0.0
Épisode 7, Récompense totale: 0.0
Épisode 8, Récompense totale: 0.0
Épisode 9, Récompense totale: 0.0
Épisode 10, Récompense totale: 0.0


### Exercice 2 : Implémentation de la méthode d'initialisation

Initialisation de la Q-Table

In [9]:
num_states = env.observation_space.n
num_actions = env.action_space.n
q_table = np.zeros((num_states, num_actions))

print("Q-Table initialisée :")
print(q_table)

Q-Table initialisée :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Exercice 3 : Implémentation du Q-Learning avec Mise à Jour

Définir les hyperparamètres : taux d'apprentissage (alpha), facteur de discount (gamma), epsilon pour l'exploration

In [15]:
alpha = 0.1           
gamma = 0.99          
epsilon = 1.0        
epsilon_decay = 0.995
min_epsilon = 0.01
num_episodes = 5000

In [16]:
# Entraînement de l’agent
episode = 0
while episode < num_episodes:
    state, info = env.reset()
    done = False

    while not done:
        # Choix de l’action : exploration ou exploitation
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state, :])

        # Exécution de l’action
        new_state, reward, done, truncated, info = env.step(action)

        # Mise à jour de la Q-Table
        old_value = q_table[state, action]
        next_max = np.max(q_table[new_state, :])
        new_value = old_value + alpha * (reward + gamma * next_max - old_value)
        q_table[state, action] = new_value

        state = new_state

    # Mise à jour du taux d’exploration avec une boucle while
    while epsilon > min_epsilon:
        epsilon = epsilon * epsilon_decay
        break  # L'epsilon est réduit une seule fois par épisode

    episode += 1

# Affichage final de la Q-Table
print("Q-Table après apprentissage :")
print(q_table)


Q-Table après apprentissage :
[[0.56304039 0.52878801 0.52780531 0.52187655]
 [0.34042933 0.31639782 0.32884872 0.50660591]
 [0.38974347 0.4174704  0.38195381 0.48001746]
 [0.26214024 0.31350918 0.22212528 0.46258896]
 [0.59552922 0.37119849 0.3969272  0.39191666]
 [0.         0.         0.         0.        ]
 [0.34254044 0.13917688 0.18413976 0.1362371 ]
 [0.         0.         0.         0.        ]
 [0.47141058 0.49137828 0.30910645 0.63788414]
 [0.45401603 0.706711   0.42827704 0.30567809]
 [0.68146431 0.41819101 0.42873238 0.3946734 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45123549 0.32109285 0.82601651 0.48856151]
 [0.72211168 0.88860642 0.76351244 0.785471  ]
 [0.         0.         0.         0.        ]]


### Exercice 4 : Évaluation des Performances de l'Agent

In [17]:
num_test_episodes = 100
successes = 0

for _ in range(num_test_episodes):
    state = env.reset()[0]
    done = False
    
    while not done:
        action = np.argmax(q_table[state])  # Toujours l'action optimale
        next_state, reward, done, truncated, info = env.step(action)
        
        if done and reward == 1:
            successes += 1
            
        state = next_state

success_rate = (successes / num_test_episodes) * 100
print(f"Taux de réussite: {success_rate}%")

Taux de réussite: 83.0%
